// Dummy data for Pre-Advice module — replace with real API data later

export const dummyRateFile = {
  shippingLine: "Maersk Line",
  shippingLineContact: {
    name: "Rajesh Kumar",
    email: "rajesh.kumar@maersk.com",
    phone: "+91-22-66487000",
    designation: "Trade Manager - Indian Subcontinent",
  },
  validity: "01-Mar-2026 to 31-Mar-2026",
  routing: "Nhava Sheva → Rotterdam → Hamburg",
  transitTime: "28 Days",
  equipmentSize: "1 x 40' HC",
  commodity: "Auto Parts & Accessories",
  por: "ICD Khodiyar (Ahmedabad)",
  pol: "Nhava Sheva (INNSA)",
  pod: "Hamburg (DEHAM)",
  finalDestination: "Hamburg, Germany",
  term: "CY/CY",
  originCharges: [
    { charges: "THC", currency: "INR", amount: 17500, unit: "Per Container" },
    { charges: "BL Fee", currency: "INR", amount: 5500, unit: "Per BL" },
    { charges: "Seal Charges", currency: "INR", amount: 750, unit: "Per Container" },
    { charges: "VGM Charges", currency: "INR", amount: 500, unit: "Per Container" },
    { charges: "CFS Charges", currency: "INR", amount: 3000, unit: "Per Container" },
  ],
  freightCharges: [
    { charges: "Ocean Freight", currency: "USD", amount: 1250, unit: "Per Container" },
    { charges: "BAF", currency: "USD", amount: 350, unit: "Per Container" },
    { charges: "CAF", currency: "USD", amount: 75, unit: "Per Container" },
    { charges: "LSS", currency: "USD", amount: 48, unit: "Per Container" },
    { charges: "ISPS", currency: "USD", amount: 15, unit: "Per BL" },
  ],
  destinationCharges: [
    { charges: "DTHC", currency: "EUR", amount: 285, unit: "Per Container" },
    { charges: "DO Charges", currency: "EUR", amount: 65, unit: "Per BL" },
    { charges: "ENS Filing", currency: "EUR", amount: 30, unit: "Per BL" },
  ],
  ddpCharges: 0,
};

export const dummyQuotation = {
  quotationNumber: "OT-EXP-2603-0042",
  dateOfBooking: "2026-03-05",
  bookedBy: "Vikram",
  customer: {
    name: "ABC Engineering Pvt. Ltd.",
    address: "Plot 15, GIDC Industrial Estate, Ahmedabad, Gujarat - 382445",
    gstin: "24AABCR1234F1Z5",
    contactPerson: "Mr. Amit Shah",
    phone: "+91-79-26301234",
    email: "amit.shah@abcengineering.in",
  },
  consignee: {
    name: "Müller Automotive GmbH",
    address: "Industriestraße 45, 80333 München, Germany",
    contactPerson: "Hans Müller",
    phone: "+49-89-123456",
    email: "hans@mueller-auto.de",
  },
  shipper: "ABC Engineering Pvt. Ltd.",
  shippingLine: "Maersk Line",
  routing: "Nhava Sheva → Rotterdam → Hamburg",
  transitTime: "28 Days",
  equipmentSize: "1 x 40' HC",
  commodity: "Auto Parts & Accessories",
  cargoWeight: "18,500 KGs",
  noOfContainers: 1,
  por: "ICD Khodiyar (Ahmedabad)",
  pol: "Nhava Sheva (INNSA)",
  pod: "Hamburg (DEHAM)",
  finalDestination: "Hamburg, Germany",
  term: "CY/CY",
  forwarding: "OmTrans Freight",
  cha: "OmTrans Customs House",
  transportation: "ICD to Port via Road",
  originCharges: [
    { charges: "THC", currency: "INR", amount: 19000, unit: "Per Container" },
    { charges: "BL Fee", currency: "INR", amount: 6500, unit: "Per BL" },
    { charges: "Seal Charges", currency: "INR", amount: 1000, unit: "Per Container" },
    { charges: "VGM Charges", currency: "INR", amount: 750, unit: "Per Container" },
    { charges: "CFS Charges", currency: "INR", amount: 4000, unit: "Per Container" },
    { charges: "CHA Charges", currency: "INR", amount: 5500, unit: "Per Shipment" },
  ],
  freightCharges: [
    { charges: "Ocean Freight", currency: "USD", amount: 1450, unit: "Per Container" },
    { charges: "BAF", currency: "USD", amount: 400, unit: "Per Container" },
    { charges: "CAF", currency: "USD", amount: 100, unit: "Per Container" },
    { charges: "LSS", currency: "USD", amount: 55, unit: "Per Container" },
    { charges: "ISPS", currency: "USD", amount: 18, unit: "Per BL" },
  ],
  destinationCharges: [
    { charges: "DTHC", currency: "EUR", amount: 310, unit: "Per Container" },
    { charges: "DO Charges", currency: "EUR", amount: 75, unit: "Per BL" },
    { charges: "ENS Filing", currency: "EUR", amount: 35, unit: "Per BL" },
  ],
  ddpCharges: 0,
  remarks: "Commodity: Non-hazardous, non-DG cargo.\nFree time at destination: 14 days.\nSubject to space & equipment availability.",
  agentDetails: "Port Agent: Müller Logistics GmbH\nContact: +49-40-987654\nEmail: ops@mueller-logistics.de",
};
