// Airlines data for auto-suggestion
export const airlines = [
  "Air India",
  "IndiGo",
  "SpiceJet",
  "Vistara",
  "AirAsia India",
  "GoAir",
  "Emirates",
  "Qatar Airways",
  "Etihad Airways",
  "Singapore Airlines",
  "Cathay Pacific",
  "Thai Airways",
  "Malaysia Airlines",
  "Turkish Airlines",
  "Lufthansa",
  "British Airways",
  "Air France",
  "KLM Royal Dutch Airlines",
  "Swiss International Air Lines",
  "Austrian Airlines",
  "American Airlines",
  "United Airlines",
  "Delta Air Lines",
  "FedEx Express",
  "UPS Airlines",
  "DHL Aviation",
  "Cargolux",
  "Korean Air Cargo",
  "Cathay Pacific Cargo",
  "Emirates SkyCargo",
  "Qatar Airways Cargo",
  "Singapore Airlines Cargo",
  "Lufthansa Cargo",
  "Air China Cargo",
  "China Airlines Cargo",
  "China Southern Cargo",
  "Japan Airlines (JAL)",
  "All Nippon Airways (ANA)",
  "Asiana Airlines",
  "EVA Air",
  "China Eastern Airlines",
  "Ethiopian Airlines",
  "Kenya Airways",
  "South African Airways",
  "EgyptAir",
  "Air Canada",
  "WestJet",
  "Alaska Airlines",
  "Southwest Airlines",
  "JetBlue Airways",
  "Qantas Airways",
  "Air New Zealand",
  "Virgin Australia",
  "Aeroflot",
  "LOT Polish Airlines",
  "Finnair",
  "SAS Scandinavian Airlines",
  "Iberia",
  "TAP Air Portugal",
  "Alitalia",
  "Aegean Airlines",
  "El Al Israel Airlines",
  "Saudia",
  "Gulf Air",
  "Oman Air",
  "Kuwait Airways",
  "Royal Jordanian",
  "Garuda Indonesia",
  "Philippine Airlines",
  "Vietnam Airlines",
  "Air Asia X",
  "Scoot",
  "Jetstar Airways",
  "Xiamen Airlines",
  "Hainan Airlines",
  "Shenzhen Airlines",
  "Sichuan Airlines",
  "Air India Express",
  "Alliance Air",
  "Blue Dart Aviation",
  "Copa Airlines",
  "LATAM Airlines",
  "Avianca",
  "Aeromexico",
  "Volaris",
  "Interjet",
  "Azul Brazilian Airlines",
  "GOL Linhas Aéreas",
].sort();
