// Airport of Departure data for auto-suggestion
// Includes major national and international airports
export const airportsOfDeparture = [
  // Indian Airports
  "Indira Gandhi International Airport (DEL) - New Delhi",
  "Chhatrapati Shivaji Maharaj International Airport (BOM) - Mumbai",
  "Kempegowda International Airport (BLR) - Bengaluru",
  "Chennai International Airport (MAA) - Chennai",
  "Netaji Subhas Chandra Bose International Airport (CCU) - Kolkata",
  "Rajiv Gandhi International Airport (HYD) - Hyderabad",
  "Cochin International Airport (COK) - Kochi",
  "Sardar Vallabhbhai Patel International Airport (AMD) - Ahmedabad",
  "Pune Airport (PNQ) - Pune",
  "Dabolim Airport (GOI) - Goa",
  "Jaipur International Airport (JAI) - Jaipur",
  "Lokpriya Gopinath Bordoloi International Airport (GAU) - Guwahati",
  "Thiruvananthapuram International Airport (TRV) - Trivandrum",
  "Calicut International Airport (CCJ) - Kozhikode",
  "Chandigarh International Airport (IXC) - Chandigarh",
  "Lucknow Airport (LKO) - Lucknow",
  "Biju Patnaik International Airport (BBI) - Bhubaneswar",
  "Coimbatore International Airport (CJB) - Coimbatore",
  "Visakhapatnam Airport (VTZ) - Visakhapatnam",
  "Mangalore International Airport (IXE) - Mangalore",
  "Srinagar Airport (SXR) - Srinagar",
  "Devi Ahilya Bai Holkar Airport (IDR) - Indore",
  "Vadodara Airport (BDQ) - Vadodara",
  "Nagpur Airport (NAG) - Nagpur",
  "Imphal Airport (IMF) - Imphal",
  "Varanasi Airport (VNS) - Varanasi",
  "Patna Airport (PAT) - Patna",
  "Bagdogra Airport (IXB) - Bagdogra",
  "Agartala Airport (IXA) - Agartala",
  "Ranchi Airport (IXR) - Ranchi",
  
  // Middle East
  "Dubai International Airport (DXB) - Dubai, UAE",
  "Abu Dhabi International Airport (AUH) - Abu Dhabi, UAE",
  "Hamad International Airport (DOH) - Doha, Qatar",
  "King Khalid International Airport (RUH) - Riyadh, Saudi Arabia",
  "King Abdulaziz International Airport (JED) - Jeddah, Saudi Arabia",
  "Kuwait International Airport (KWI) - Kuwait City, Kuwait",
  "Muscat International Airport (MCT) - Muscat, Oman",
  "Bahrain International Airport (BAH) - Manama, Bahrain",
  "Sharjah International Airport (SHJ) - Sharjah, UAE",
  "Al Maktoum International Airport (DWC) - Dubai, UAE",
  
  // Asia Pacific
  "Singapore Changi Airport (SIN) - Singapore",
  "Hong Kong International Airport (HKG) - Hong Kong",
  "Suvarnabhumi Airport (BKK) - Bangkok, Thailand",
  "Kuala Lumpur International Airport (KUL) - Kuala Lumpur, Malaysia",
  "Beijing Capital International Airport (PEK) - Beijing, China",
  "Shanghai Pudong International Airport (PVG) - Shanghai, China",
  "Guangzhou Baiyun International Airport (CAN) - Guangzhou, China",
  "Tokyo Narita International Airport (NRT) - Tokyo, Japan",
  "Tokyo Haneda Airport (HND) - Tokyo, Japan",
  "Incheon International Airport (ICN) - Seoul, South Korea",
  "Taipei Taoyuan International Airport (TPE) - Taipei, Taiwan",
  "Jakarta Soekarno-Hatta International Airport (CGK) - Jakarta, Indonesia",
  "Manila Ninoy Aquino International Airport (MNL) - Manila, Philippines",
  "Ho Chi Minh City Tan Son Nhat International Airport (SGN) - Ho Chi Minh City, Vietnam",
  "Hanoi Noi Bai International Airport (HAN) - Hanoi, Vietnam",
  
  // Europe
  "London Heathrow Airport (LHR) - London, UK",
  "London Gatwick Airport (LGW) - London, UK",
  "Paris Charles de Gaulle Airport (CDG) - Paris, France",
  "Frankfurt Airport (FRA) - Frankfurt, Germany",
  "Amsterdam Airport Schiphol (AMS) - Amsterdam, Netherlands",
  "Munich Airport (MUC) - Munich, Germany",
  "Madrid-Barajas Airport (MAD) - Madrid, Spain",
  "Barcelona-El Prat Airport (BCN) - Barcelona, Spain",
  "Rome Fiumicino Airport (FCO) - Rome, Italy",
  "Zurich Airport (ZRH) - Zurich, Switzerland",
  "Vienna International Airport (VIE) - Vienna, Austria",
  "Brussels Airport (BRU) - Brussels, Belgium",
  "Copenhagen Airport (CPH) - Copenhagen, Denmark",
  "Stockholm Arlanda Airport (ARN) - Stockholm, Sweden",
  "Oslo Airport (OSL) - Oslo, Norway",
  "Helsinki-Vantaa Airport (HEL) - Helsinki, Finland",
  "Athens International Airport (ATH) - Athens, Greece",
  "Istanbul Airport (IST) - Istanbul, Turkey",
  "Lisbon Portela Airport (LIS) - Lisbon, Portugal",
  
  // North America
  "John F. Kennedy International Airport (JFK) - New York, USA",
  "Los Angeles International Airport (LAX) - Los Angeles, USA",
  "Chicago O'Hare International Airport (ORD) - Chicago, USA",
  "Dallas/Fort Worth International Airport (DFW) - Dallas, USA",
  "San Francisco International Airport (SFO) - San Francisco, USA",
  "Miami International Airport (MIA) - Miami, USA",
  "Seattle-Tacoma International Airport (SEA) - Seattle, USA",
  "Boston Logan International Airport (BOS) - Boston, USA",
  "Newark Liberty International Airport (EWR) - Newark, USA",
  "Toronto Pearson International Airport (YYZ) - Toronto, Canada",
  "Vancouver International Airport (YVR) - Vancouver, Canada",
  "Montreal-Pierre Elliott Trudeau International Airport (YUL) - Montreal, Canada",
  
  // Africa
  "Cairo International Airport (CAI) - Cairo, Egypt",
  "O.R. Tambo International Airport (JNB) - Johannesburg, South Africa",
  "Cape Town International Airport (CPT) - Cape Town, South Africa",
  "Addis Ababa Bole International Airport (ADD) - Addis Ababa, Ethiopia",
  "Jomo Kenyatta International Airport (NBO) - Nairobi, Kenya",
  "Mohammed V International Airport (CMN) - Casablanca, Morocco",
  
  // Oceania
  "Sydney Kingsford Smith Airport (SYD) - Sydney, Australia",
  "Melbourne Airport (MEL) - Melbourne, Australia",
  "Brisbane Airport (BNE) - Brisbane, Australia",
  "Auckland Airport (AKL) - Auckland, New Zealand",
  
  // South America
  "São Paulo/Guarulhos International Airport (GRU) - São Paulo, Brazil",
  "Mexico City International Airport (MEX) - Mexico City, Mexico",
  "Jorge Chávez International Airport (LIM) - Lima, Peru",
  "El Dorado International Airport (BOG) - Bogotá, Colombia",
  "Buenos Aires Ezeiza International Airport (EZE) - Buenos Aires, Argentina",
].sort();
