// Foreign Destinations - Major Ports and Cities (alphabetically sorted)
export const foreignDestinations = [
  // Middle East
  "Dubai, UAE",
  "Jebel Ali, UAE",
  "Abu Dhabi, UAE",
  "Sharjah, UAE",
  "Doha, Qatar",
  "Muscat, Oman",
  "Sohar, Oman",
  "Salalah, Oman",
  "Kuwait City, Kuwait",
  "Dammam, Saudi Arabia",
  "Jeddah, Saudi Arabia",
  "Riyadh, Saudi Arabia",
  "Bahrain",
  // Southeast Asia
  "Singapore",
  "Port Klang, Malaysia",
  "Penang, Malaysia",
  "Kuala Lumpur, Malaysia",
  "Bangkok, Thailand",
  "Laem Chabang, Thailand",
  "Ho Chi Minh City, Vietnam",
  "Haiphong, Vietnam",
  "Manila, Philippines",
  "Jakarta, Indonesia",
  "Surabaya, Indonesia",
  "Yangon, Myanmar",
  // East Asia
  "Shanghai, China",
  "Ningbo, China",
  "Shenzhen, China",
  "Guangzhou, China",
  "Qingdao, China",
  "Tianjin, China",
  "Hong Kong",
  "Tokyo, Japan",
  "Yokohama, Japan",
  "Osaka, Japan",
  "Kobe, Japan",
  "Busan, South Korea",
  "Incheon, South Korea",
  "Seoul, South Korea",
  // Europe
  "Rotterdam, Netherlands",
  "Hamburg, Germany",
  "Antwerp, Belgium",
  "Felixstowe, UK",
  "London, UK",
  "Southampton, UK",
  "Le Havre, France",
  "Barcelona, Spain",
  "Genoa, Italy",
  "Istanbul, Turkey",
  // North America
  "Los Angeles, USA",
  "Long Beach, USA",
  "New York, USA",
  "Newark, USA",
  "Savannah, USA",
  "Houston, USA",
  "Miami, USA",
  "Seattle, USA",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Toronto, Canada",
  // Australia & New Zealand
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Adelaide, Australia",
  "Auckland, New Zealand",
  // Africa
  "Durban, South Africa",
  "Cape Town, South Africa",
  "Lagos, Nigeria",
  "Mombasa, Kenya",
  "Dar es Salaam, Tanzania",
  // South America
  "Santos, Brazil",
  "Buenos Aires, Argentina",
  "Valparaiso, Chile",
].sort();