// Foreign Destinations - Major Ports and Cities (alphabetically sorted)
export const foreignDestinations = [
  // Middle East
  "Dubai, UAE",
  "Jebel Ali, UAE",
  "Abu Dhabi, UAE",
  "Sharjah, UAE",
  "Doha, Qatar",
  "Muscat, Oman",
  "Sohar, Oman",
  "Salalah, Oman",
  "Kuwait City, Kuwait",
  "Dammam, Saudi Arabia",
  "Jeddah, Saudi Arabia",
  "Riyadh, Saudi Arabia",
  "Bahrain",
  "Khalifa Bin Salman, Bahrain",
  "Shuwaikh, Kuwait",
  "Shuaiba, Kuwait",
  "Hamad, Qatar",
  "Aden, Yemen",
  "Hodeidah, Yemen",
  "Aqaba, Jordan",
  "Bandar Abbas, Iran",
  // South Asia
  "Colombo, Sri Lanka",
  "Chittagong, Bangladesh",
  "Male, Maldives",
  // Southeast Asia
  "Singapore",
  "Port Klang, Malaysia",
  "Penang, Malaysia",
  "Kuala Lumpur, Malaysia",
  "Bangkok, Thailand",
  "Laem Chabang, Thailand",
  "Ho Chi Minh City, Vietnam",
  "Haiphong, Vietnam",
  "Manila, Philippines",
  "Jakarta, Indonesia",
  "Surabaya, Indonesia",
  "Belawan, Indonesia",
  "Semarang, Indonesia",
  "Yangon, Myanmar",
  "Sihanoukville, Cambodia",
  // East Asia
  "Shanghai, China",
  "Ningbo, China",
  "Shenzhen, China",
  "Guangzhou, China",
  "Qingdao, China",
  "Tianjin, China",
  "Hong Kong",
  "Tokyo, Japan",
  "Yokohama, Japan",
  "Osaka, Japan",
  "Kobe, Japan",
  "Nagoya, Japan",
  "Busan, South Korea",
  "Incheon, South Korea",
  "Seoul, South Korea",
  // Europe
  "Rotterdam, Netherlands",
  "Hamburg, Germany",
  "Antwerp, Belgium",
  "Felixstowe, UK",
  "London, UK",
  "Southampton, UK",
  "Le Havre, France",
  "Dunkerque, France",
  "Barcelona, Spain",
  "Valencia, Spain",
  "Algeciras, Spain",
  "Vigo, Spain",
  "Bilbao, Spain",
  "Genoa, Italy",
  "La Spezia, Italy",
  "Ravenna, Italy",
  "Venice, Italy",
  "Istanbul, Turkey",
  "Gemlik, Turkey",
  "Aliaga, Turkey",
  "Ambarli, Turkey",
  "Gebze, Turkey",
  "Evyap, Turkey",
  "Piraeus, Greece",
  "Koper, Slovenia",
  "Rijeka, Croatia",
  "Ploče, Croatia",
  "Varna, Bulgaria",
  "Gdynia, Poland",
  "Copenhagen, Denmark",
  "Aarhus, Denmark",
  "Saint Petersburg, Russia",
  "Vladivostok, Russia",
  // North America
  "Los Angeles, CA",
  "Long Beach, CA",
  "Oakland, CA",
  "Seattle, WA",
  "New York, NY",
  "Newark, NJ",
  "Savannah, GA",
  "Charleston, SC",
  "Houston, TX",
  "Miami, FL",
  "Vancouver, BC",
  "Montreal, QC",
  "Toronto, ON",
  "Edmonton, AB",
  "Manzanillo, Mexico",
  "Veracruz, Mexico",
  "Altamira, Mexico",
  "Lazaro Cardenas, Mexico",
  // Central America & Caribbean
  "Balboa, Panama",
  "Puerto Quetzal, Guatemala",
  "Managua, Nicaragua",
  "Rio Haina, Dominican Republic",
  // South America
  "Santos, Brazil",
  "Navegantes, Brazil",
  "Buenos Aires, Argentina",
  "Montevideo, Uruguay",
  "Valparaíso, Chile",
  "San Antonio, Chile",
  "Callao, Peru",
  "Guayaquil, Ecuador",
  "Buenaventura, Colombia",
  // Australia & New Zealand
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Adelaide, Australia",
  "Auckland, New Zealand",
  "Port Moresby, Papua New Guinea",
  // Africa
  "Durban, South Africa",
  "Cape Town, South Africa",
  "Lagos (Apapa), Nigeria",
  "Tincan, Nigeria",
  "Mombasa, Kenya",
  "Dar es Salaam, Tanzania",
  "Tema, Ghana",
  "Takoradi, Ghana",
  "Dakar, Senegal",
  "Douala, Cameroon",
  "Luanda, Angola",
  "Beira, Mozambique",
  "Djibouti",
  "Berbera, Somalia",
  "Sudan Port, Sudan",
  "Alexandria, Egypt",
  "Ain Sokhna, Egypt",
  "Tripoli, Libya",
  "Alger, Algeria",
  "Port Louis, Mauritius",
  // Middle East - Additional
  "Umm Qasr, Iraq",
  "Beirut, Lebanon",
  "Haifa, Israel",
  // India - ICDs and Ports
  "ACTL Faridabad (HR)",
  "Ahmedabad ICD (AMD)",
  "Ankleshwar ICD (AKV)",
  "Bangalore ICD (WFD)",
  "Bhiwadi ICD (BWD)",
  "Chennai Port (TN)",
  "Coimbatore ICD (CBE)",
  "Cochin Port (KL)",
  "Dadri ICD (UP)",
  "Dhamra Port (OD)",
  "Dighi ICD (MH)",
  "Durgapur ICD (DGP)",
  "Ennore Port (TN)",
  "Gangavaram Port (AP)",
  "Garhi Harsaru ICD (HR)",
  "Haldia Port (WB)",
  "Hazira Port (GJ)",
  "Hyderabad ICD (HYD)",
  "Irugur ICD (IRUGUR)",
  "Jaipur ICD (JPR)",
  "Jattipur / Panipat ICD (HR)",
  "Jodhpur ICD (RJ)",
  "Kakinada Port (AP)",
  "Kanpur ICD (KNP)",
  "Kandla Port (GJ)",
  "Khodiyar ICD (KHODIYAR)",
  "Kolkata Port (WB)",
  "Krishnapatnam Port (AP)",
  "KSH ICD (MH)",
  "Loni ICD (LON)",
  "Ludhiana ICD (LDH)",
  "Madurai ICD (MDU)",
  "Modinagar ICD (UP)",
  "Moradabad ICD (MBQ)",
  "Mormugao Port (GA)",
  "Mumbai Port (MH)",
  "Mundra Port (GJ)",
  "Nagpur ICD (NGP)",
  "New Mangalore Port (KA)",
  "Nhava Sheva (MH)",
  "Palwal ICD (HR)",
  "Pali ICD (HR)",
  "Paradip Port (OD)",
  "Patli ICD (HR)",
  "Patparganj ICD (DL)",
  "Pipavav Port (GJ)",
  "Piyala ICD (HR)",
  "Port Blair Port (AN)",
  "Sonepat ICD (HR)",
  "Sanand ICD (GJ)",
  "TUMB ICD (GJ)",
  "Tughlakabad ICD (DL)",
  "Tuticorin Port (TN)",
  "Visakhapatnam Port (AP)",
  "Vizhinjam International Seaport (KL)",
  // Kazakhstan
  "Almaty, Kazakhstan",
  // Lome
  "Lome, Togo",
].sort();
