// Indian Ports (alphabetically sorted)
export const indianPorts = [
  "Chennai Port (TN)",
  "Cochin Port (KL)",
  "Dhamra Port (OD)",
  "Ennore Port (TN)",
  "Gangavaram Port (AP)",
  "Haldia Port (WB)",
  "Hazira Port (GJ)",
  "Kakinada Port (AP)",
  "Kandla Port (GJ)",
  "Kolkata Port (WB)",
  "Krishnapatnam Port (AP)",
  "Mormugao Port (GA)",
  "Mumbai Port (MH)",
  "Mundra Port (GJ)",
  "New Mangalore Port (KA)",
  "Nhava Sheva (MH)",
  "Paradip Port (OD)",
  "Pipavav Port (GJ)",
  "Port Blair Port (AN)",
  "Tuticorin Port (TN)",
  "Visakhapatnam Port (AP)",
  "Vizhinjam International Seaport (KL)",
  "Jebel Ali",
  "Shuwaikh",
  "Sohar",
  "Bahrain",
  "Colombo",
  "Kelang Port",
  "Aden",
  "Umm Qasr",
  "Abu Dhabi",
  "Dammam",
  "Hamad",
  "Sudan Port",
  "Chittagong",
  "Singapore",
  "Hodeidah",
  "Aqaba",
  "Sharjah",
  "Shuaiba",
  "Djibouti",
  "Yangon",
  "Berbera",
  "Bandar Abbas",
  "Jeddah",
  "Riyadh",
  "Salalah",
  "Jakarta",
  "Belawan",
  "Surabaya",
  "Ho Chi Minh City",
  "Haiphong",
  "Ain Sokhna",
  "Shanghai",
  "Ningbo",
  "Qingdao",
].sort();
