// Indian Ports (alphabetically sorted)
export const indianPorts = [
  "Chennai Port, Tamil Nadu",
  "Cochin Port, Kerala",
  "Ennore Port, Tamil Nadu",
  "Hazira Port, Gujarat",
  "JNPT (Jawaharlal Nehru Port), Maharashtra",
  "Kamarajar Port, Tamil Nadu",
  "Kandla Port, Gujarat",
  "Kolkata Port, West Bengal",
  "Mangalore Port, Karnataka",
  "Mormugao Port, Goa",
  "Mumbai Port, Maharashtra",
  "Mundra Port, Gujarat",
  "Paradip Port, Odisha",
  "Pipavav Port, Gujarat",
  "Sikka Port, Gujarat",
  "Tuticorin Port, Tamil Nadu",
  "Visakhapatnam Port, Andhra Pradesh",
  "Dahej Port, Gujarat",
  "Haldia Port, West Bengal",
  "Krishnapatnam Port, Andhra Pradesh",
  "Dhamra Port, Odisha",
  "Kakinada Port, Andhra Pradesh",
  "Magdalla Port, Gujarat",
  "Porbandar Port, Gujarat",
  "Okha Port, Gujarat",
  "Bhavnagar Port, Gujarat",
  "Veraval Port, Gujarat",
  "Nagapattinam Port, Tamil Nadu",
  "Karaikal Port, Puducherry",
  "Cuddalore Port, Tamil Nadu",
  "Port Blair, Andaman and Nicobar",
].sort();