// ICD locations in India (alphabetically sorted)
export const icdLocations = [
  "ICD Agra, Uttar Pradesh",
  "ICD Ahmedabad, Gujarat",
  "ICD Ajmer, Rajasthan",
  "ICD Amingaon, Assam",
  "ICD Anaparthy, Andhra Pradesh",
  "ICD Bangalore, Karnataka",
  "ICD Bhadohi, Uttar Pradesh",
  "ICD Bhilwara, Rajasthan",
  "ICD Bhiwadi, Rajasthan",
  "ICD Coimbatore, Tamil Nadu",
  "ICD Dadri, Uttar Pradesh",
  "ICD Durgapur, West Bengal",
  "ICD Faridabad (Ballabhgarh), Haryana",
  "ICD Garhi Harsaru, Haryana",
  "ICD Guntur, Andhra Pradesh",
  "ICD Hyderabad, Telangana",
  "ICD Jaipur, Rajasthan",
  "ICD Jallandhar, Punjab",
  "ICD Jodhpur, Rajasthan",
  "ICD Kanpur, Uttar Pradesh",
  "ICD Kota, Rajasthan",
  "ICD Loni, Uttar Pradesh",
  "ICD Ludhiana, Punjab",
  "ICD Moradabad, Uttar Pradesh",
  "ICD Nagpur, Maharashtra",
  "ICD Nasik, Maharashtra",
  "ICD Patli Gurgaon, Haryana",
  "ICD Pithampur, Madhya Pradesh",
  "ICD Piyala Rewari, Haryana",
  "ICD Pune, Maharashtra",
  "ICD Raipur, Chhattisgarh",
  "ICD Rewari, Haryana",
  "ICD Sachhin, Gujarat",
  "ICD Singanalur, Tamil Nadu",
  "ICD Talegaon, Maharashtra",
  "ICD TKD, Delhi",
  "ICD Vadodara, Gujarat",
  "ICD Varanasi, Uttar Pradesh",
  "ICD Whitefield Bangalore, Karnataka",
].sort();