// ICD locations (alphabetically sorted)
export const icdLocations = [
  // India - ICDs and Ports
  "ACTL Faridabad (HR)",
  "Ahmedabad ICD (AMD)",
  "Ankleshwar ICD (AKV)",
  "Bangalore ICD (WFD)",
  "Bhiwadi ICD (BWD)",
  "Chennai Port (TN)",
  "Coimbatore ICD (CBE)",
  "Cochin Port (KL)",
  "Dadri ICD (UP)",
  "Dhamra Port (OD)",
  "Dighi ICD (MH)",
  "Durgapur ICD (DGP)",
  "Ennore Port (TN)",
  "Gangavaram Port (AP)",
  "Garhi Harsaru ICD (HR)",
  "Haldia Port (WB)",
  "Hazira Port (GJ)",
  "Hyderabad ICD (HYD)",
  "Irugur ICD (IRUGUR)",
  "Jaipur ICD (JPR)",
  "Jattipur / Panipat ICD (HR)",
  "Jodhpur ICD (RJ)",
  "Kakinada Port (AP)",
  "Kanpur ICD (KNP)",
  "Kandla Port (GJ)",
  "Khodiyar ICD (KHODIYAR)",
  "Kolkata Port (WB)",
  "Krishnapatnam Port (AP)",
  "KSH ICD (MH)",
  "Loni ICD (LON)",
  "Ludhiana ICD (LDH)",
  "Madurai ICD (MDU)",
  "Modinagar ICD (UP)",
  "Moradabad ICD (MBQ)",
  "Mormugao Port (GA)",
  "Mumbai Port (MH)",
  "Mundra Port (GJ)",
  "Nagpur ICD (NGP)",
  "New Mangalore Port (KA)",
  "Nhava Sheva (MH)",
  "Palwal ICD (HR)",
  "Pali ICD (HR)",
  "Paradip Port (OD)",
  "Patli ICD (HR)",
  "Patparganj ICD (DL)",
  "Pipavav Port (GJ)",
  "Piyala ICD (HR)",
  "Port Blair Port (AN)",
  "Sanand ICD (GJ)",
  "Sonepat ICD (HR)",
  "TUMB ICD (GJ)",
  "Tughlakabad ICD (DL)",
  "Tuticorin Port (TN)",
  "Visakhapatnam Port (AP)",
  "Vizhinjam International Seaport (KL)",
  // Middle East
  "Abu Dhabi",
  "Aqaba",
  "Bahrain",
  "Bandar Abbas",
  "Dammam",
  "Hamad",
  "Jebel Ali",
  "Jeddah",
  "Riyadh",
  "Salalah",
  "Sharjah",
  "Shuaiba",
  "Shuwaikh",
  "Sohar",
  // Asia
  "Ain Sokhna",
  "Belawan",
  "Chittagong",
  "Colombo",
  "Haiphong",
  "Ho Chi Minh City",
  "Jakarta",
  "Kelang Port",
  "Ningbo",
  "Qingdao",
  "Shanghai",
  "Singapore",
  "Surabaya",
  "Yangon",
  // Africa
  "Aden",
  "Berbera",
  "Djibouti",
  "Hodeidah",
  "Sudan Port",
  "Umm Qasr",
].sort();
