// Shipping lines data (alphabetically sorted)
export const shippingLines = [
  "Maersk Line",
  "Arkas Line",
  "CMA CGM",
  "COSCO",
  "Evergreen",
  "Hapag-Lloyd",
  "HMM",
  "MSC",
  "ONE",
  "OOCL",
  "PIL",
  "SCI",
  "Yang Ming",
  "Zim",
  "Wan Hai",
  "Matson Navigation",
  "KMTC",
  "Arkas Line",
  "TS Lines",
  "IRISL",
  "X-Press Feeders",
].sort();
